# Generated by Django 5.0.7 on 2024-10-07 08:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SleepDiary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                (
                    "start",
                    models.CharField(max_length=20, verbose_name="start event date"),
                ),
                ("end", models.CharField(max_length=20, verbose_name="end event date")),
            ],
            options={
                "db_table": "SleepDiary",
            },
        ),
    ]
