# Generated by Django 5.0.7 on 2024-10-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sleepdiary",
            name="end",
            field=models.CharField(max_length=50, verbose_name="end event date"),
        ),
        migrations.AlterField(
            model_name="sleepdiary",
            name="start",
            field=models.CharField(max_length=50, verbose_name="start event date"),
        ),
    ]
